name: reflectable_issue_307
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.3.0

dependencies:
  reflectable: any

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
